---
- name: Install the timescaledb repo
  copy:
    dest: /etc/yum.repos.d/timescaledb.repo
    content: |
      [timescaledb]
      name = Copr modules repo for timescaledb
      baseurl = https://download.copr.fedorainfracloud.org/results/abompard/timescaledb/modules/epel-8-$basearch+timescaledb-master-20210730083523/latest/$basearch
      gpgcheck=0
      gpgkey=https://download.copr.fedorainfracloud.org/results/abompard/timescaledb/pubkey.gpg
      repo_gpgcheck=0
      enabled = 1

- name: Install the postgresql:12 module
  copy:
    dest: /etc/dnf/modules.d/postgresql.module
    content: |
      [postgresql]
      name=postgresql
      stream=12
      profiles=
      state=enabled

- name: Install the timescaledb module
  copy:
    dest: /etc/dnf/modules.d/timescaledb.module
    content: |
      [timescaledb]
      name=timescaledb
      stream=master
      profiles=
      state=enabled

- name: Enable the python39 module
  copy:
    dest: /etc/dnf/modules.d/python39.module
    content: |
      [python39]
      name=python39
      stream=3.9
      profiles=
      state=enabled

- name: Install RPM packages
  dnf:
    name:
      - python39
      - python39-psycopg2
      - postgresql-server
      - timescaledb
      # This is necessary for ansible's postgresql modules
      - python3-psycopg2
    state: present

- name: Setup the postgresql DB
  command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf

- name: Add timescaledb to postgresql config
  lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    regexp: ^shared_preload_libraries =
    line: "shared_preload_libraries = 'timescaledb'"

- name: Configure access to postgresql
  postgresql_pg_hba:
    dest: /var/lib/pgsql/data/pg_hba.conf
    contype: host
    databases: all
    users: all
    address: "{{item}}"
    method: md5
  loop:
    - 127.0.0.1/32
    - ::1/128

- name: Start postgresql
  service:
    name: postgresql
    enabled: yes
    state: started

- block:
    - name: Create the user
      postgresql_user:
        name: datanommer
        password: datanommer

    - name: Create the database
      postgresql_db:
        name: messages
        owner: datanommer

    - name: Activate timescaledb
      postgresql_ext:
        name: timescaledb
        db: messages
  become: yes
  become_user: postgres
  become_method: sudo

- name: Make connection easier
  copy:
    dest: /home/vagrant/.pgpass
    content: "*:*:messages:datanommer:datanommer\n"
    owner: vagrant
    group: vagrant
    mode: 0600
