queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Checks
      - check-success=Licenses (models)
      - check-success=Licenses (consumer)
      - check-success=Licenses (commands)
      - check-success=Unit tests (3.10, models)
      - check-success=Unit tests (3.10, consumer)
      - check-success=Unit tests (3.10, commands)
      - check-success=Unit tests (3.11, models)
      - check-success=Unit tests (3.11, consumer)
      - check-success=Unit tests (3.11, commands)


pull_request_rules:

- name: Merge on approval
  actions:
    queue:
      name: default
      method: rebase
  conditions:
    - label!=no-mergify
    - -draft
    - approved-reviews-by=@fedora-infra/data-team
    - "#changes-requested-reviews-by=0"
    - check-success=Checks
    - check-success=Licenses (models)
    - check-success=Licenses (consumer)
    - check-success=Licenses (commands)
    - check-success=Unit tests (3.10, models)
    - check-success=Unit tests (3.10, consumer)
    - check-success=Unit tests (3.10, commands)
    - check-success=Unit tests (3.11, models)
    - check-success=Unit tests (3.11, consumer)
    - check-success=Unit tests (3.11, commands)
