[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "S", "B", "RUF"]
ignore = ["RUF012"]

[tool.ruff.lint.isort]
lines-after-imports = 2
order-by-type = false
known-first-party = ["datanommer"]

[tool.ruff.lint.per-file-ignores]
"*/tests/*" = ["S101", "E501"]
"tools/towncrier/get-authors.py" = ["S602", "S603", "S607"]

[tool.pytest.ini_options]
addopts = "-v --cov-config ../pyproject.toml --cov --cov-report term-missing --cov-report html --cov-report xml"

[tool.coverage.run]
branch = true
source = ["datanommer"]

[tool.coverage.paths]
source = ["datanommer"]

[tool.coverage.report]
fail_under = 98
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
]
omit = [
    "datanommer/models/testing/*",
]
